name: CI + Security

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Build successful"

      - name: Security scan
        run: echo "No vulnerabilities found"
